@startuml

title "Component Diagram of JaPong"

package Server {
    folder "Process" as gameManagementProcess {
        [Game State Management]
        interface "/game/input" as GameStateManagementCommand
        [Game State Management] -- GameStateManagementCommand
        interface "/game/management" as GameState
        GameState - [Game State Management]
        interface "/game/court" as Court
        [Game State Management] --> Court
    }
    folder "Process" as roomManagementProcess {
        [Room Management]
        interface "/room/management" as RoomManagementCommand
        [Room Management] -- RoomManagementCommand
        GameState <- [Room Management]
    }
}

package Client {
    folder "Process" as clientProcess {
        [Form] -up-> RoomManagementCommand
        [Game Rendering] -up-> Court
        [Game Input] -up-> GameStateManagementCommand
    }
}

@enduml