@startuml

title "Component Diagram of JaPong"

folder "Process" as gameManagementProcess {
    [Game Engine]
    [Game Engine] "*" - "1" [Node I/O]
    interface "HTTP /games" as NodeIOIF
    [Node I/O] - NodeIOIF
    interface "WebSocket\n/commandDict" as GameCommandDictIF
    [Node I/O] -- GameCommandDictIF
    interface "WebSocket\n/board" as GameBoardIF
    [Node I/O] -- GameBoardIF
    interface "WebSocket\n/gameOver" as GameOverIF
    [Node I/O] -- GameOverIF
}
folder "Process" as roomManagementProcess {
    [Cluster Management]
    interface "HTTP /games" as ClusterManagementIF
    [Cluster Management] -- ClusterManagementIF
    NodeIOIF <- [Cluster Management]
}

package Client {
    folder "Process" as clientProcess {
        [Form] -up-> ClusterManagementIF
        [Game Rendering] -up-> GameBoardIF
        [Game Rendering] -up-> GameOverIF
        [Game Input] -up-> GameCommandDictIF
    }
}

@enduml