@startuml
title "Deployment Diagram of JaPong"

actor Player
cloud "GCP" {
  rectangle "Asia-Northeast" {
    node "Cloud Run" as RunAN {
      component "Node I/O" as NodeIOAN
      component "Game Engine" as GameEngineAN
    }
  }
  rectangle "US-Central" {
    node "Cloud Run" as ClusterManagementNode {
      component "Cluster Management" as ClusterManagement
    }
    node "Cloud Run" as RunUC {
      component "Node I/O" as NodeIOUC
      component "Game Engine" as GameEngineUC
    }
    node "Virtual Machine" {
      component "Web Server" as WebServer
    }
  }
}

WebServer <-- Player
ClusterManagement <-- Player
NodeIOAN <-- Player
GameEngineAN "*" - "1" NodeIOAN
GameEngineUC "*" - "1" NodeIOUC
NodeIOAN <-- ClusterManagement
NodeIOUC <-- ClusterManagement
@enduml