name: GitHub Actions Demo
on: [push]
jobs:
  ProcessOpenAPI:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - run: mkdir swagger-ui-tmp
    - run: echo "The ${{ github.repositort }} repository has been cloned to the runner."
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui-tmp/clusterManagement
        spec-file: "${{ github.workspace }}/api/clusterManagement/openapi.yaml"
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui-tmp/nodeIO
        spec-file: "${{ github.workspace }}/api/nodeio/openapi.yaml"
    - id: upload-files
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: swagger-ui-tmp/clusterManagement
        destination: japong-api-doc
    - id: upload-files
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: swagger-ui-tmp/nodeIO
        destination: japong-api-doc